// v1.11 — DOCX export with optional branding (logo + color)
import { NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase-server";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  ImageRun,
  Footer,
} from "docx";
import { z } from "zod";

const requestSchema = z.object({
  content: z.string().min(1),
  headline: z.string().optional(),
  address: z.string().optional(),
  format: z.string().optional(),
});

export async function POST(request: Request) {
  try {
    const supabase = await createServerSupabaseClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { content, headline, address, format } = requestSchema.parse(body);

    // Get branding if user is on a team
    let logoImageData: Buffer | null = null;
    let brandColor = "2563eb";
    let brokerageName = "";

    const { data: membership } = await supabase
      .from("team_members")
      .select("team_id")
      .eq("user_id", user.id)
      .limit(1)
      .single();

    if (membership) {
      const { data: team } = await supabase
        .from("teams")
        .select("name, brand_logo_url, brand_primary_color")
        .eq("id", membership.team_id)
        .single();

      if (team) {
        brokerageName = team.name || "";
        if (team.brand_primary_color) {
          brandColor = team.brand_primary_color.replace("#", "");
        }
        if (team.brand_logo_url) {
          try {
            const logoRes = await fetch(team.brand_logo_url);
            if (logoRes.ok) {
              logoImageData = Buffer.from(await logoRes.arrayBuffer());
            }
          } catch {
            // Logo fetch failed, continue without it
          }
        }
      }
    }

    // Get user info for footer
    const { data: dbUser } = await supabase
      .from("users")
      .select("full_name, email")
      .eq("id", user.id)
      .single();

    const agentName = dbUser?.full_name || dbUser?.email || "";

    // Build document sections
    const headerChildren: Paragraph[] = [];

    if (logoImageData) {
      headerChildren.push(
        new Paragraph({
          children: [
            new ImageRun({
              data: logoImageData,
              transformation: { width: 120, height: 40 },
              type: "png",
            }),
          ],
        })
      );
    }

    if (address) {
      headerChildren.push(
        new Paragraph({
          children: [
            new TextRun({ text: address, bold: true, size: 20, color: brandColor }),
          ],
          spacing: { after: 100 },
        })
      );
    }

    if (headline) {
      headerChildren.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [
            new TextRun({ text: headline, bold: true, size: 28, color: brandColor }),
          ],
          spacing: { after: 200 },
        })
      );
    }

    const bodyParagraphs = content.split("\n").filter(Boolean).map(
      (para) =>
        new Paragraph({
          children: [new TextRun({ text: para, size: 22 })],
          spacing: { after: 120 },
        })
    );

    const footerText = [agentName, brokerageName].filter(Boolean).join(" | ");

    const doc = new Document({
      sections: [
        {
          properties: {},
          footers: footerText
            ? {
                default: new Footer({
                  children: [
                    new Paragraph({
                      alignment: AlignmentType.CENTER,
                      children: [
                        new TextRun({
                          text: `Generated by ${footerText}`,
                          size: 16,
                          color: "999999",
                        }),
                      ],
                    }),
                  ],
                }),
              }
            : undefined,
          children: [...headerChildren, ...bodyParagraphs],
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    const filename = address
      ? `${address.replace(/[^a-zA-Z0-9]/g, "_")}_${format || "listing"}.docx`
      : `listing_${format || "export"}.docx`;

    const uint8 = new Uint8Array(buffer);
    return new Response(uint8, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("DOCX export error:", error);
    return NextResponse.json(
      { message: error instanceof Error ? error.message : "Export failed" },
      { status: 500 }
    );
  }
}
