// v1.11 — PDF export (simple HTML-to-PDF via browser print, returns styled HTML)
import { NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase-server";
import { z } from "zod";

const requestSchema = z.object({
  content: z.string().min(1),
  headline: z.string().optional(),
  address: z.string().optional(),
  format: z.string().optional(),
  bullets: z.array(z.string()).optional(),
  cta: z.string().optional(),
});

export async function POST(request: Request) {
  try {
    const supabase = await createServerSupabaseClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { content, headline, address, bullets, cta } = requestSchema.parse(body);

    // Get branding
    let logoUrl = "";
    let brandColor = "#2563eb";
    let brokerageName = "";

    const { data: membership } = await supabase
      .from("team_members")
      .select("team_id")
      .eq("user_id", user.id)
      .limit(1)
      .single();

    if (membership) {
      const { data: team } = await supabase
        .from("teams")
        .select("name, brand_logo_url, brand_primary_color")
        .eq("id", membership.team_id)
        .single();

      if (team) {
        brokerageName = team.name || "";
        if (team.brand_primary_color) brandColor = team.brand_primary_color;
        if (team.brand_logo_url) logoUrl = team.brand_logo_url;
      }
    }

    const { data: dbUser } = await supabase
      .from("users")
      .select("full_name, email")
      .eq("id", user.id)
      .single();

    const agentName = dbUser?.full_name || dbUser?.email || "";
    const footerText = [agentName, brokerageName].filter(Boolean).join(" | ");

    // Build print-ready HTML for flyer/PDF
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    @page { size: letter; margin: 0.75in; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; line-height: 1.6; }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid ${brandColor}; padding-bottom: 12px; margin-bottom: 24px; }
    .logo { max-height: 48px; }
    .address { font-size: 12px; color: #64748b; }
    h1 { color: ${brandColor}; font-size: 28px; margin: 0 0 16px; }
    .body { font-size: 14px; }
    .bullets { list-style: none; padding: 0; margin: 20px 0; }
    .bullets li { padding: 8px 0; padding-left: 20px; position: relative; font-size: 14px; }
    .bullets li::before { content: ''; position: absolute; left: 0; top: 14px; width: 8px; height: 8px; background: ${brandColor}; border-radius: 50%; }
    .cta { background: ${brandColor}; color: white; padding: 12px 24px; border-radius: 8px; display: inline-block; font-weight: bold; margin-top: 20px; font-size: 14px; }
    .footer { border-top: 1px solid #e2e8f0; padding-top: 12px; margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    ${logoUrl ? `<img src="${logoUrl}" alt="Logo" class="logo">` : "<div></div>"}
    <div class="address">${address || ""}</div>
  </div>
  ${headline ? `<h1>${headline}</h1>` : ""}
  <div class="body">${content.split("\n").map((p) => `<p>${p}</p>`).join("")}</div>
  ${bullets && bullets.length > 0 ? `<ul class="bullets">${bullets.map((b) => `<li>${b}</li>`).join("")}</ul>` : ""}
  ${cta ? `<div class="cta">${cta}</div>` : ""}
  ${footerText ? `<div class="footer">Generated by ${footerText}</div>` : ""}
</body>
</html>`;

    return new Response(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="listing-flyer.html"`,
      },
    });
  } catch (error) {
    console.error("PDF export error:", error);
    return NextResponse.json(
      { message: error instanceof Error ? error.message : "Export failed" },
      { status: 500 }
    );
  }
}
