// v1.4 — Fair Housing Checker explainer page (public, SEO target)
import { Home, ShieldCheck, AlertTriangle, Check } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Fair Housing Compliance Checker for MLS Listings — ListEze",
  description:
    "Every listing description generated by ListEze is automatically scanned for Fair Housing Act violations. Flagged terms are highlighted, explained, and one-click fixable.",
};

const CATEGORIES = [
  {
    name: "Familial Status",
    examples: ["family-friendly", "perfect for kids", "no children", "adults only"],
    guidance: "Describe features (fenced yard, multiple bedrooms) instead of targeting families or excluding them.",
  },
  {
    name: "Race & National Origin",
    examples: ["exclusive neighborhood", "integrated", "ethnic", "safe neighborhood", "low crime"],
    guidance: "Describe specific amenities and location features. Never imply racial composition or make crime/safety claims.",
  },
  {
    name: "Religion",
    examples: ["near churches", "christian community", "near temple"],
    guidance: "Reference non-religious landmarks. Do not describe the religious character of a neighborhood.",
  },
  {
    name: "Disability",
    examples: ["walking distance", "able-bodied", "handicapped"],
    guidance: "Use distance measurements ('0.5 miles to') and 'accessible' instead of ableist language.",
  },
  {
    name: "Sex / Gender",
    examples: ["master bedroom", "mother-in-law suite", "man cave"],
    guidance: "Use 'primary bedroom', 'in-law suite', 'bonus room'. NAR recommended this change in 2020.",
  },
];

export default function FairHousingCheckerPage() {
  return (
    <div className="bg-card text-foreground font-sans">
      {/* Header */}
      <header className="sticky top-0 z-40 backdrop-blur bg-background/80 border-b border-border">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <Home className="h-7 w-7 text-blue-600" />
              <span className="text-xl font-extrabold tracking-tight">ListEze</span>
            </Link>
            <Link href="/login">
              <Button className="bg-blue-600 hover:bg-blue-700 text-white rounded-xl px-4 py-2 text-sm font-semibold">
                Start Free Trial
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="py-16 lg:py-24 bg-gradient-to-b from-green-50 to-white dark:from-slate-950 dark:to-slate-900">
        <div className="mx-auto max-w-4xl px-4 text-center">
          <div className="inline-flex items-center gap-2 rounded-full bg-green-100 px-4 py-1.5 text-sm font-medium text-green-700 mb-6">
            <ShieldCheck className="w-4 h-4" />
            Built into every generation
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold leading-tight">
            Fair Housing Compliance Checker
          </h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            Every MLS description generated by ListEze is automatically scanned for
            Fair Housing Act violations. Flagged terms are highlighted, explained,
            and one-click fixable.
          </p>
        </div>
      </section>

      {/* How it works */}
      <section className="py-16 bg-card">
        <div className="mx-auto max-w-4xl px-4">
          <h2 className="text-2xl font-bold mb-8">How the scanner works</h2>
          <div className="grid sm:grid-cols-3 gap-6">
            <Card className="p-6 border border-border rounded-2xl">
              <div className="text-sm font-bold text-blue-600 mb-2">Pass 1: Term Matching</div>
              <p className="text-sm text-muted-foreground">
                Regex scan against 40+ known flagged terms from HUD guidance, NAR
                Code of Ethics, and state bulletins.
              </p>
            </Card>
            <Card className="p-6 border border-border rounded-2xl">
              <div className="text-sm font-bold text-blue-600 mb-2">Pass 2: AI Context Scan</div>
              <p className="text-sm text-muted-foreground">
                Claude Haiku analyzes the full text for subtle coded language and
                context-dependent issues the regex misses.
              </p>
            </Card>
            <Card className="p-6 border border-border rounded-2xl">
              <div className="text-sm font-bold text-blue-600 mb-2">One-Click Fix</div>
              <p className="text-sm text-muted-foreground">
                Click &ldquo;Fix All&rdquo; and Claude Sonnet rewrites the description to
                remove violations while preserving meaning and tone.
              </p>
            </Card>
          </div>
        </div>
      </section>

      {/* Categories */}
      <section className="py-16 bg-muted">
        <div className="mx-auto max-w-4xl px-4">
          <h2 className="text-2xl font-bold mb-8">Protected categories we scan for</h2>
          <div className="space-y-6">
            {CATEGORIES.map((cat) => (
              <Card key={cat.name} className="p-6 border border-border rounded-2xl">
                <h3 className="font-bold text-lg">{cat.name}</h3>
                <div className="mt-2 flex flex-wrap gap-2">
                  {cat.examples.map((ex) => (
                    <span key={ex} className="inline-flex items-center gap-1 rounded-full bg-red-100 text-red-700 px-3 py-1 text-xs font-medium">
                      <AlertTriangle className="w-3 h-3" />
                      {ex}
                    </span>
                  ))}
                </div>
                <p className="mt-3 text-sm text-muted-foreground">{cat.guidance}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 bg-gradient-to-r from-blue-700 to-purple-600 text-white">
        <div className="mx-auto max-w-4xl px-4 text-center">
          <h2 className="text-3xl font-extrabold">Compliance built in, not bolted on</h2>
          <p className="mt-2 text-white/90">
            Every ListEze generation is scanned automatically. No extra steps.
          </p>
          <div className="mt-6 flex items-center justify-center gap-4">
            <Link href="/login">
              <Button className="bg-white hover:bg-white/90 text-blue-700 rounded-2xl px-6 py-3 font-semibold shadow">
                Start Free Trial
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-card border-t border-border py-8">
        <div className="mx-auto max-w-4xl px-4 text-center text-sm text-muted-foreground">
          <p>ListEze&apos;s fair housing scanner is a compliance aid, not legal advice. Always consult your broker or attorney for compliance questions.</p>
        </div>
      </footer>
    </div>
  );
}
